support llama-stack 0.2.22 (#671)

diff --git a/roles/chatbot/templates/chatbot.deployment.yaml.j2 b/roles/chatbot/templates/chatbot.deployment.yaml.j2
--- a/roles/chatbot/templates/chatbot.deployment.yaml.j2
+++ b/roles/chatbot/templates/chatbot.deployment.yaml.j2
@@ -99,6 +99,20 @@ spec:
       - name: ansible-chatbot
         image: {{ _chatbot_image }}
         imagePullPolicy: '{{ image_pull_policy }}'
+        command:
+          - /bin/sh
+          - -c
+          - |
+            if [ -z "$PROVIDER_VECTOR_DB_ID" ]; then
+              if [ -f "/rag/llama_stack_vector_db/provider_vector_db_id.ind" ]; then
+                export PROVIDER_VECTOR_DB_ID=$(cat /rag/llama_stack_vector_db/provider_vector_db_id.ind)
+                echo "Loaded PROVIDER_VECTOR_DB_ID: $PROVIDER_VECTOR_DB_ID"
+              else
+                echo "ERROR: PROVIDER_VECTOR_DB_ID is not set and file /rag/llama_stack_vector_db/provider_vector_db_id.ind was not found"
+                exit 1
+              fi
+            fi
+            exec /.llama/entrypoint.sh /usr/bin/python3.12
         env:
           - name: LLAMA_STACK_CONFIG_DIR
             value: /.llama/data
